# DO NOT MODIFY -- auto-generated by Apache Cordova
# DO NOT MODIFY -- auto-generated by Apache Cordova

platform :ios, '9.0'

abstract_target 'ENOS_Mobile' do
	pod 'EnvHybrid', :tag => '3.0.0', :git => 'http://git.envisioncn.com/FE/mobile-framework-hybrid-ios.git'
  pod 'SVGKit'
  pod 'CocoaLumberjack'
  pod 'UMCCommon'
  pod 'UMCPush'
  pod 'UMCSecurityPlugins'
  pod 'KVOController'
  
  target 'HybridWind' do
    
  end

  target 'HybridWind Dev' do

  end

  target 'HybridWind SHDL' do

  end

  target 'HybridWind HBJT' do

  end

  target 'HybridWind AppStore' do

  end
  
end
